export const VANITY_TO_FILE = {
  "Butterfly Knife": "knife_butterfly",
  knife: "knife",
  knife_t: "knife_t",
  Knife: "knife",
  Bayonet: "knife_bayonet",
  "Talon Knife": "knife_widowmaker",
  Karambit: "knife_karambit",
  "M9 Bayonet": "knife_m9_bayonet",
  "Shadow Daggers": "knife_push",
  "Skeleton Knife": "knife_skeleton",
  "Ursus Knife": "knife_ursus",
  "Bowie Knife": "knife_bowie",
  "Falchion Knife": "knife_falchion",
  "Flip Knife": "knife_flip",
  "Gut Knife": "knife_gut",
  "Huntsman Knife": "knife_tactical",
  "Navaja Knife": "knife_gypsy_jackknife",
  "Paracord Knife": "knife_cord",
  "Stiletto Knife": "knife_stiletto",
  "Survival Knife": "knife_canis",
  "Classic Knife": "knife_css",
  "Nomad Knife": "knife_outdoor",
  "Kukri Knife": "knife_kukri",
  "CZ75-Auto": "cz75a-icon",
  "Desert Eagle": "deagle-icon",
  "Dual Berettas": "dual-elite-icon",
  "Five-SeveN": "five-seven-icon",
  "Glock-18": "glock-icon",
  P2000: "p2000-icon",
  P250: "p250-icon",
  "R8 Revolver": "revolver-icon",
  "Tec-9": "tec9-icon",
  "USP-S": "usp_silencer-icon",
  "AK-47": "ak47-icon",
  AUG: "aug-icon",
  AWP: "awp-icon",
  FAMAS: "famas-icon",
  G3SG1: "g3sg1-icon",
  "Galil AR": "galilar-icon",
  "M4A1-S": "m4a1_silencer-icon",
  M4A4: "m4a4-icon",
  "SCAR-20": "scar20-icon",
  "SG 553": "sg553-icon",
  "SSG 08": "ssg08-icon",
  "MAC-10": "mac10-icon",
  "MP5-SD": "mp5sd-icon",
  MP7: "mp7-icon",
  MP9: "mp9-icon",
  "PP-Bizon": "bizon-icon",
  P90: "p90-icon",
  "UMP-45": "ump45-icon",
  "MAG-7": "mag7-icon",
  Nova: "nova-icon",
  "Sawed-Off": "sawed-off-icon",
  XM1014: "xm1014-icon",
  M249: "m249-icon",
  Negev: "negev-icon",
  "Zeus x27": "zeus-icon",
  "Smoke Grenade": "smoke-grenade-icon",
  "High Explosive Grenade": "he-grenade-icon",
  "Incendiary Grenade": "incendiary-grenade-icon",
  Flashbang: "flashbang-icon",
  Molotov: "molotov-icon",
  "C4 Explosive": "bomb-icon",
};

// let a = [
//   "decoy-icon",
//   "helmet-icon",
//   "kevlar-icon",
//   "knife-icon",
//   "knife",
//   "knifegg",
//   "knife_bayonet",
//   "knife_bowie",
//   "knife_butterfly",
//   "knife_canis",
//   "knife_cord",
//   "knife_css",
//   "knife_falchion",
//   "knife_flip",
//   "knife_gut",
//   "knife_gypsy_jackknife",
//   "knife_karambit",
//   "knife_kukri",
//   "knife_m9_bayonet",
//   "knife_outdoor",
//   "knife_push",
//   "knife_skeleton",
//   "knife_stiletto",
//   "knife_t",
//   "knife_tactical",
//   "knife_twinblade",
//   "knife_ursus",
//   "knife_widowmaker",
//   "m4a1-icon",
//   "m4a1-silencer-off-icon",
//   "usps-silencer-off-icon",
//   "world-icon",
// ];
